### ISSUE TITLE
Cancel button on add-event modal does nothing if there is an error

### ISSUE THREAD

**Issue by mypark** [vonovak/react-native-add-calendar-event#1]
When adding a new event - if you pass a null or invalid startDate, there is no way to close the modal.  Pressing the cancel button in the modal does nothing.

New event modal's modal button works correctly if there are no errors in the date.

**Comment by vonovak** [comment]
I assume you're talking about the ios version of the module. Can you post a repro code? I cannot reproduce the inability to close the modal. As for nulls, the module expects a valid string, is there a reason you need to pass null?

**Comment by mypark** [comment]
I don't need to pass in a null - but just worried about error conditions since it creates an unrecoverable state that locks the UI and forces the user to force quit the app.
```
  addToCalendar = async () => {
    const { Event } = this.props.data;
    // error occurs if Event.startTime is null
    const startTime = moment.unix(Event.startTime);
    const eventConfig = {
      title: Event.game,
      startDate: startTime.format('YYYY-MM-DDTHH:mm:ss.SSSZZ'),
      location: Event.location.address,
      notes: Event.headline,
    };

    try {
      await AddCalendarEvent.presentNewCalendarEventDialog(eventConfig);
    } catch (error) {
      Alert.alert('Error', `Could not add to calendar ${error}`);
    }
  }
```

**Comment by vonovak** [comment]
I am still not able to reproduce - if I pass in a null date, I get the red screen. Then I can press `dismiss` and `close` the modal. If I build the app as release, the red screen is not shown and modal can also be dismissed. The only case when modal cannot be dismissed is if the red screen shows up and you tap `reload`, but nothing can be done about that.

can you tell me *exactly* how to get to a state where the user won't be able to dismiss the modal? Thanks!

**Comment by mypark** [comment]
ah ok I think it happens when i reload - not an issue then - let's close

**Comment by mypark** [comment]
Ah yes it happens when I reload.  You are right - will close this issue.
