### ISSUE TITLE
Date is off by 4 hours in iOS dialogue

### ISSUE THREAD

**Issue by agersoncgps** [vonovak/react-native-add-calendar-event#11]
I am passing in a raw date from an ics file "20171010T160000" which has the format "YYYYMMDDTHHmmss". The correct local time (New York CIty) is 4pm.

Using moment.js I format it with 

`var date = moment(date, "YYYYMMDDTHHmmss").local().format('YYYY-MM-DDTHH:mm:ss.SSSZZ')`

The output to console is correct "2017-10-10T16:00:00.000-0400", but when I pass it in to eventConfig as the "startDate" property, iOS displays the time as four hours ahead. It should be 4pm but displays as 8pm.

![screenshot 2017-10-09 17 39 36](https://user-images.githubusercontent.com/336441/31359682-01f2949a-ad19-11e7-8c73-acc82ce0995d.png)

**Comment by vonovak** [comment]
um, just to make sure - is the time zone in your emulator correct?

**Comment by agersoncgps** [comment]
Duh, yes, thats must be it. Strangely, the simulator is supposed to use the date/time settings of the Mac OS, which are correct. I will investigate it further, but clearly not an issue with this module.
