### ISSUE TITLE
iOS 14 - Chose a custom calendar makes the app crash

### ISSUE THREAD

**Issue by MayoudP** [vonovak/react-native-add-calendar-event#110]
Hello,
I have some users complaining that since they've updated their phone with **iOS 14**. When using the feature calendar-event within my app, and trying to chose a custom calendars where to save the event, as soon as they click, the app crash. 

Does anyone got the same issue ? 

<img width="443" alt="Screenshot 2020-10-06 at 17 44 06" src="https://user-images.githubusercontent.com/48682041/95224987-98ff8380-07fb-11eb-87b5-cadb9772d38c.png">

**Comment by NeRo8** [comment]
Add this ```<key>NSCalendarsUsageDescription</key>
	<string></string>
	<key>NSContactsUsageDescription</key>
	<string></string>``` to Info.plist file

**Comment by MayoudP** [comment]
> NSContactsUsageDescription

I already have `NSCalendarsUsageDescription`in my Info.plist. And I don't see why `NSContactsUsageDescription`should be used for this librairie, we don't need the 'Contacts', it's a Private' information which I'm not a huge fan to include in my code...

**Comment by sapradev** [comment]
@MayoudP if you find any solution please let me know, my app crashes on iOS 14 when i try to AddCalendarEvent.presentEventViewingDialog(event) or AddCalendarEvent.presentEventCreatingDialog(eventConfig). However app works fine on iOS 13 and iOS 12, Also on Android 10 works fine.

**Comment by MayoudP** [comment]
I resigned myself adding the NSContactsUsageDescription in the Info.plist as suggested above.
