### ISSUE TITLE
IOS: always returns {action:"CANCELED"} 

### ISSUE THREAD

**Issue by samratbanna** [vonovak/react-native-add-calendar-event#112]
Hi all!

When I open app first time successfully add event then then after dialog opens and dismiss immediately It returns the response is:

**`{action: "CANCELED"}`**

Does anybody know why this might be happening?

Thank you!

**Comment by russ666** [comment]
@samratbanna did you find any fix?

**Comment by KrisGilicze** [comment]
Had the same issue, I was able to fix it by changing all my
`AddCalendarEvent.presentEventCreatingDialog(config).then(...)` to async await syntax.
Hope this helps

**Comment by russ666** [comment]
@KrisGilicze doesn't work for me. it opens only first time

**Comment by perfectAlways1028** [comment]
Is there anybody who fixed this issue?

**Comment by Rananjaya** [comment]
Same issues. anyone had solution for
 this. Thanks.

**Comment by K-OBrien-Phase2** [comment]
Having the same issue, anyone found a solution?
