### ISSUE TITLE
Crash on iOS 14

### ISSUE THREAD

**Issue by sapradev** [vonovak/react-native-add-calendar-event#118]
Hi,
I used this npm on iOS 13 and 12 it worked fine for me, but lately when iOS 14 came and while testing on those devices the app crashes when i try to add calendar event. Is there any solution to this? i have even updated npm version to latest

**Comment by KrisGilicze** [comment]
Had the same issue, I was able to fix it by changing all my
`AddCalendarEvent.presentEventCreatingDialog(config).then(...)` to async await syntax.
Hope this helps

**Comment by sapradev** [comment]
Hi @KrisGilicze,
Thanks for your response,
I have already used async function, but my integration is bit different unable to use await, throws error. Can you provide pseudo code / example dummy code how did you exactly used it?

**Comment by hhgandhi** [comment]
@devs96 , Did you find any solution for iOS 14?

**Comment by devs96** [comment]
Yes by using async and await.
Await addcalendarevent.presentEventViewDialog

**Comment by mirzahayat** [comment]
Hope so it will help full.
try to add permission in info.plist for IOS
<key>NSCalendarsUsageDescription</key>
<string>This app requires access to the calendar</string>
