### ISSUE TITLE
IOS app crashes when trying to type in the Location field on the Calendar event.

### ISSUE THREAD

**Issue by latircoleetti** [vonovak/react-native-add-calendar-event#17]
It seems to be consistently crashing on IOS when trying to type into the Location field. Is this issue known or am I doing something incorrect?

**Comment by vonovak** [comment]
@latircoleetti seems weird to me that the js module should be responsible because the modal is n ios functionality

I'm just geussing that it might be something with location permissions, but without a stacktrace it's hard to help

**Comment by latircoleetti** [comment]
Hi @vonovak thanks for getting back to me.

I resolved the issue. It turns out on IOS you need 3 permissions to allow it to work correctly.

```
<key>NSCalendarsUsageDescription</key>
	<string></string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string></string>
	<key>NSContactsUsageDescription</key>
	<string></string>
```

It's all working now 👍

**Comment by Amit1405** [comment]
Above solution not working , any other can help please
