### ISSUE TITLE
iOS - Permission denied to access Native calendar issue

### ISSUE THREAD

**Issue by rbabel** [vonovak/react-native-add-calendar-event#18]
If permission is denied to access the native calendar in iOS, the App gets stuck, and permission is not asked again. This doesn't happen in Android.

**Comment by vonovak** [comment]
@rbabel if you can you post a minimal repro, that would be appreciated

**Comment by rbabel** [comment]
@vonovak - When invoking the calendar for the first time from the iOS App using this library, a pop up appears asking "The App would like to access your calendar". If the user selects "Don't Allow", subsequent clicks on the button to add the event to the calendar doesn't do anything.

**Comment by vonovak** [comment]
Hmm, not sure but isn't that default ios behavior? I'm inclined to think
that ios just remembers the user's decision and doesn't bother them next
time.  How do other apps with similar functionality work?

**Comment by rbabel** [comment]
If the user selects "Don't Allow', then the user will never will be able to use this feature to add an event ever, unless they delete the App and re-install. Either the permissions shouldn't be asked at all or user be allowed to make a choice again when clicking on Add event.

**Comment by vonovak** [comment]
@rbabel they will be able to change the permissions in settings. Unfortunately I don't have an ios device at my disposal atm so I cannot verify the normal ios behavior.

**Comment by rbabel** [comment]
@vonovak thanks, yes that seems to work. But from a customer experience, shouldn't clicking on the Add event prompt the user to go to Settings? eg a message like this: The App does not have access to your calendars. To enable access, tap Settings and turn on Calendars.

**Comment by vonovak** [comment]
like I said, I don't know what the standard ios behavior is here. However, you get the information about whether user did not give the permissions in the `catch` part of 

```js
import * as AddCalendarEvent from 'react-native-add-calendar-event';

const eventConfig = {
  title,
  // and other options
};

AddCalendarEvent.presentNewCalendarEventDialog(eventConfig)
  .then(eventId => {
    //handle success (receives event id) or dismissing the modal (receives false)
    if (eventId) {
      console.warn(eventId);
    } else {
      console.warn('dismissed');
    }
  })
  .catch((error: string) => {
    // handle error such as when user rejected permissions
    console.warn(error);
  });
};
```


So you can react to it as it pleases you.

**Comment by rbabel** [comment]
thanks @vonovak for your quick response. I had missed to see that. This should work.

**Comment by vonovak** [comment]
@vin7974 I think the module is not correctly linked in your case

**Comment by AndreyPatseiko** [comment]
Had this problem, after installing manually all work fine.

**Comment by amitbravo** [comment]
@vin7974 I forgot to run cd ios && pod install after installing at RN 0.6.xx
