### ISSUE TITLE
iOS17 Calendar Permission Changes

### ISSUE THREAD

**Issue by kohchihao** [vonovak/react-native-add-calendar-event#180]
There are new changes to the iOS17 Calendar permission where 2 new permissions are introduced `full access` and `write only`. 

This will cause the `presentEventCreatingDialog` to be broken on iOS17 because when checking the permission and requesting via `requestAccessToEntityType` will cause the app to throw an error. Specifically the `requestAccessToEntityType` is deprecated on iOS17 and 2 new methods are introduced. 

Ref: 
- https://developer.apple.com/documentation/technotes/tn3153-adopting-api-changes-for-eventkit-in-ios-macos-and-watchos
- https://developer.apple.com/documentation/eventkit/ekeventstore/4162274-requestwriteonlyaccesstoeventswi?language=objc
- https://developer.apple.com/documentation/eventkit/ekeventstore/4162272-requestfullaccesstoeventswithcom?language=objc

I think other libraries are facing the same issues as well https://github.com/wmcmahan/react-native-calendar-events/issues/440

**Comment by leonardohenriquedev** [comment]
A workaround that i made is request permissions by react-native-calendar-events like this: 

`import ReactNativeCalendarEvents from "react-native-calendar-events";`
`import { presentEventCreatingDialog } from "react-native-add-calendar-event";`

```
    ReactNativeCalendarEvents.requestPermissions().then((response) => {
      if (response === "authorized")
        try {
          presentEventCreatingDialog({ title: "" })
            .then((eventInfo) => {
              console.log(JSON.stringify(eventInfo));
            })
            .catch((error) => {
              console.log(error);
            });
        } catch (error) {
          console.log("calendar error:", error);
        }
    });
```

But first you need to make this change in your RNCalendarEvents.m file from react-native-calendar-events https://github.com/agent8/react-native-calendar-events/commit/368206ca3228cea97d8dfb913107bb61012062a2

**Comment by phatlaunchdeck** [comment]
> A workaround that i made is request permissions by react-native-calendar-events like this:
> 
> `import ReactNativeCalendarEvents from "react-native-calendar-events";` `import { presentEventCreatingDialog } from "react-native-add-calendar-event";`
> 
> ```
>     ReactNativeCalendarEvents.requestPermissions().then((response) => {
>       if (response === "authorized")
>         try {
>           presentEventCreatingDialog({ title: "" })
>             .then((eventInfo) => {
>               console.log(JSON.stringify(eventInfo));
>             })
>             .catch((error) => {
>               console.log(error);
>             });
>         } catch (error) {
>           console.log("calendar error:", error);
>         }
>     });
> ```
> 
> But first you need to make this change in your RNCalendarEvents.m file from react-native-calendar-events [agent8/react-native-calendar-events@368206c](https://github.com/agent8/react-native-calendar-events/commit/368206ca3228cea97d8dfb913107bb61012062a2)

Would it be simpler by just calling `Permissions.check()` from `react-native-permissions` so that we don't have to modify `react-native-calendar-events`?

**Comment by claudiozam** [comment]
@phatlaunchdeck we also have problems in **react-native-permissions** https://github.com/zoontek/react-native-permissions/issues/804

**Comment by remipou** [comment]
I made it work this way: https://github.com/vonovak/react-native-add-calendar-event/compare/master...remipou:react-native-add-calendar-event:master
Don't forget to add a `NSCalendarsWriteOnlyAccessUsageDescription` key in your info.plist

**Comment by tholmgren** [comment]
> I made it work this way: [master...remipou:react-native-add-calendar-event:master](https://github.com/vonovak/react-native-add-calendar-event/compare/master...remipou:react-native-add-calendar-event:master) Don't forget to add a `NSCalendarsWriteOnlyAccessUsageDescription` key in your info.plist (#182)

Thank you, Remipou.  This worked great for me!

**Comment by GeorgiIvanovPXL** [comment]
NSCalendarsUsageDescription has been deprecated. 
If your app needs read and write access to a person’s calendar data, use NSCalendarsFullAccessUsageDescription instead. If your app needs to create events in a person’s default calendar, use NSCalendarsWriteOnlyAccessUsageDescription 
instead.

[https://developer.apple.com/documentation/bundleresources/information_property_list/nscalendarsusagedescription]

**Comment by GeorgiIvanovPXL** [comment]
> > I made it work this way: [master...remipou:react-native-add-calendar-event:master](https://github.com/vonovak/react-native-add-calendar-event/compare/master...remipou:react-native-add-calendar-event:master) Don't forget to add a `NSCalendarsWriteOnlyAccessUsageDescription` key in your info.plist (#182)
> 
> Thank you, Remipou. This worked great for me!

Is there any way to mergen this PR??

**Comment by GeorgiIvanovPXL** [comment]
Any updates?

**Comment by GeorgiIvanovPXL** [comment]
Any updates on this PR??

**Comment by vonovak** [comment]
Thus library no longer deals with permissions.
Please use rn-permissions or similar, as documented in the Readme.

**Comment by gkasireddy202** [comment]
unauthorized to access calendar error using permission:NSCalendarsWriteOnlyAccessUsageDescription and created event with permission:NSCalendarsFullAccessUsageDescription

    componentDidMount() {
        RNCalendarEvents.requestPermissions()
        .then(res => {
          alert('Premission Response', res);
        })
        .catch(error => {
          console.log(error);
        });
}
