### ISSUE TITLE
Cannot read property 'presentNewEventDialog' of undefined

### ISSUE THREAD

**Issue by paperview** [vonovak/react-native-add-calendar-event#19]
![simulator screen shot - iphone 6 - 2018-02-19 at 12 56 41](https://user-images.githubusercontent.com/2209256/36393249-688cf9de-1574-11e8-9016-e73a0bfa3e16.png)

in my code i import `import * as AddCalendarEvent from 'react-native-add-calendar-event';`

and using (for example)

```
const CalendarButton = () => (
  <TextButton onPress={() => {
    AddCalendarEvent.presentNewCalendarEventDialog({})
      .then(eventId => {
        //handle success (receives event id) or dismissing the modal (receives false)
        if (eventId) {
          console.warn(eventId);
        } else {
          console.warn('dismissed');
        }
      })
      .catch((error: string) => {
        // handle error such as when user rejected permissions
        console.warn(error);
    });

  }} text="Calendar" />
);
```

and I get the attached error.  I have linked and followed your instructions.  Any ideas?  Thanks

**Comment by vonovak** [comment]
I think you have not linked correctly. Do you use pods or not?

**Comment by paperview** [comment]
I just ran `react-native link react-native-add-calendar-event` to link and added the library in the project.

do I have to run a pod install?  or what is the alternative?  thanks

**Comment by paperview** [comment]
in the example project, changing react-native version to 53 in package.json seems to break it

**Comment by vonovak** [comment]
if you use pods, `react-native link` probably added the podspec to your podfile, in which case you need to run pod install. If not, please verify that the library is under `link binary with libraries` in the build settings in xcode.

**Comment by paperview** [comment]
I used yarn and added manually and things seem to be working now.

FYI i think my problem stemmed from also using the RNFirebase pod along with your project somehow.  the podfile configuration after the npm part of your readme led to some very weird bugs after pod install.  i have no idea what was going on, but i got it working the manual way.  thanks for the help.

**Comment by vonovak** [comment]
I have updated the readme, and will close this since it seems to be solved
