### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by basequatro** [vonovak/react-native-add-calendar-event#2]
Looks like the event screen is hard coded in English, I've tried to change language of the phone (IOS) settings without success. Is there any other setting on xCode we have to set?

**Comment by vonovak** [comment]
Good question. There are some strings that are hardcoded (when asking for calendar permission) but nothing about the language of the modal.

Unfortunately I don't know what needs to be done to change the language, please let me know when you find out how to do it.

**Comment by vonovak** [comment]
@basequatro you can do it by going to project settings in xcode and adding the language there, in the "Localizations" tab.

**Comment by basequatro** [comment]
Thanks! also works if installing react-native-i18n

**Comment by ceulain** [comment]
Hello, i'm trying to change language but i can't. Can you show me step by step how to do that, please ? Thanks

**Comment by vonovak** [comment]
@ceulain https://stackoverflow.com/questions/18425945/xcode-5-and-localization-of-xib-files

**Comment by ceulain** [comment]
@vonovak thanks It works perfectly 😄

**Comment by whalemare** [comment]
This link more helpful for me:

https://stackoverflow.com/a/12428028/5662244
