### ISSUE TITLE
AddCalendarEvent.presentCalendarEventDialog is not a function

### ISSUE THREAD

**Issue by systemride** [vonovak/react-native-add-calendar-event#26]
![screen shot 2018-03-14 at 4 20 53 pm](https://user-images.githubusercontent.com/1361/37436185-da6b300c-27a3-11e8-9919-a19e14a4233d.png)

However, `presentEventDialog` works fine. Either the function name or the documentation should be updated.

**Comment by vonovak** [comment]
ouch, thanks for noticing that! I just fixed the readme.
