### ISSUE TITLE
Warning on iOS in console

### ISSUE THREAD

**Issue by systemride** [vonovak/react-native-add-calendar-event#27]
![screen shot 2018-03-14 at 4 23 54 pm](https://user-images.githubusercontent.com/1361/37436262-415aa414-27a4-11e8-8e03-d14ac251f473.png)

I'm using RN 0.53.3

I believe it needs this inside of the implementation:

```
+ (BOOL)requiresMainQueueSetup {
  return YES;
}
```

**Comment by vonovak** [comment]
hi, thanks for the report. Why do you think we need to return `YES`? I believe returning `NO` is appropriate here.

**Comment by systemride** [comment]
Sorry, I shouldn't have implied that it needs to be `YES`, I was just providing the snippet that addresses the issue. All good if `NO` makes more sense here.

**Comment by vonovak** [comment]
fixed in 1.0.1, thanks again for noticing that
