### ISSUE TITLE
Changing language

### ISSUE THREAD

**Issue by olsins** [vonovak/react-native-add-calendar-event#30]
Found the answer myself: https://stackoverflow.com/questions/18425945/xcode-5-and-localization-of-xib-files

**Comment by vonovak** [comment]
If you take a better look at the readme, you'll notice the topic is covered.

**Comment by toytonic** [comment]
Hi there. I'm having issues solving this topic. If I add a new localization in the xcode project no file for your lib appears. Only Launchscreen and the image picker lib I am using. Any help is appreciated.
