### ISSUE TITLE
How is Event ID defined?

### ISSUE THREAD

**Issue by jeveloper** [vonovak/react-native-add-calendar-event#31]
hello @vonovak  
Thanks for the great work!

I am trying to figure out a problem.

Your library returns eventID . 

however another library that also uses eventKit https://github.com/wmcmahan/react-native-calendar-events returns a list of events for the same date but contains different ID.
I understand that an ID could contain calendarID but in this case they are definitely not the same.

Very strange.

Thank you

**Comment by vonovak** [comment]
seems like usage with https://github.com/wmcmahan/react-native-calendar-events makes sense... perhaps we could make it so the module works with both identifiers.

**Comment by jeveloper** [comment]
I basically ran into this when i attempted to remove an event and noticed the identifier being different. 
At one point i thought that the ID was made up of <Calendar ID>:<event ID>  , it seemed structured that way. 

Thanks for clarification, might have to fork.

**Comment by vonovak** [comment]
@jeveloper please let me know if it works

**Comment by jeveloper** [comment]
I'm not too familiar with eventkit sdk. But do you think you might add support for accepting both types of IDs ? Passing an option e.g. { idtype = 'calendarItemIdentifier' }  so that it doesn't break your lib.

I'll propose the same to the other repo owner , i am having a parallel conversation with him :)

**Comment by vonovak** [comment]
@jeveloper you don't need to be very familiar with them. Just replace [this occurence](https://github.com/vonovak/react-native-add-calendar-event/blob/master/ios/AddCalendarEvent.m#L130) and [this one](https://github.com/vonovak/react-native-add-calendar-event/blob/master/ios/AddCalendarEvent.m#L183) with the appropriate calls and it should work. I may add support for both event types, but it will take a few days.

**Comment by jeveloper** [comment]
Thanks @vonovak

**Comment by vonovak** [comment]
@jeveloper I got to do it on the train home: please try out this branch: https://github.com/vonovak/react-native-add-calendar-event/tree/itemIdentifierInterop

and please let me know if editing events works with both types of identifiers on ios

**Comment by jeveloper** [comment]
Thanks , i will try it right now.

Btw i noticed that when editing , i can't override the title and other fields if i provide them , i guess that's a limitation.

**Comment by jeveloper** [comment]
Wanted to keep you updated, It works fine on android , the IDS are the same obviously . Is that normal that the ID is "4" on android ? 
Mine is actually linked to google calendar, i would think that it would be some sort of long thats big.

Will check IOS now.

**Comment by jeveloper** [comment]
Hey 
Its working well , it can edit with caleventid.

Tested both android and ios

thank you , let me know when you merge it into master and publish

**Comment by vonovak** [comment]
published in 1.1.0
