### ISSUE TITLE
Adding on Android sometimes returns false as a return object

### ISSUE THREAD

**Issue by jeveloper** [vonovak/react-native-add-calendar-event#34]
hey @vonovak  

With more heavy use i started to notice buggy behaviour.

Its definitely Android only

Permissions are definitely set

**Comment by vonovak** [comment]
hi @jeveloper can you create a minimal repro and share it here? 

Personally, I am not using the event id functionality myself so this does not pressure me. It may be fastest if you investigate the behavior yourself and make a PR to fix this.

**Comment by jeveloper** [comment]
Hey @vonovak 

Its really not different than your example.
RN 52
Android 7.1 - samsung S7



But here are the steps:


open event dialog
pass some trivial data , title, start date, end date 
Click Cancel on Android Native Dialog


same screen 
open event dialog 
click Save on android native dialog 

At this point there is a chance that return value is FALSE for some reason


This is happening randomly

**Comment by jeveloper** [comment]
Sounds like it will work out
Sorry im not sure ill have time to work on that project
