### ISSUE TITLE
Wrong Time while adding moment utc date and time  to iOS and Android calendar

### ISSUE THREAD

**Issue by Sreekanthp74** [vonovak/react-native-add-calendar-event#38]
{ 
  endDate : "2018-04-13T17:00:00.000+00:00"
  notes : "Note."
  startDate : "2018-04-13T11:00:00.000+00:00"
  title : "Title Text"
}

I am passing thins calendar configuration but I am getting time  4:30 pm and 10:30 pm. Please help to make it correct time . Its very Important

**Comment by Sreekanthp74** [comment]
But am having this issue in Android side. Am not god at android codes. Can some one please help?

**Comment by vonovak** [comment]
You should not need to do any custom coding, this should just work if you
follow the Readme.

**Comment by ahadali** [comment]
@vonovak or anyone can provide a proper solution for this with code example? I am still facing the issue.

**Comment by Rananjaya** [comment]
Same issues here with wrong time. any fix ?
