### ISSUE TITLE
Query: Is there a way we can add reminder?

### ISSUE THREAD

**Issue by abhichourasia** [vonovak/react-native-add-calendar-event#41]
Is there a way we can set alarm or reminder before xx amount of time before the startTime of the event? I can't find Alarm option in AddCalendarEvent.presentEventDialog(eventConfig).

**Comment by vonovak** [comment]
only the options mentioned in the [readme](https://github.com/vonovak/react-native-add-calendar-event#supported-options) are supported. It is fairly easy to add more though, as seen in this PR: https://github.com/vonovak/react-native-add-calendar-event/pull/32/files

**Comment by abhichourasia** [comment]
thanks for your reply. I am not sure about parameters I need to pass in for setting notifications. I am sure it's not boolean. Maybe reminder minutes? Do you have any document I can refer to and make changes.

**Comment by vonovak** [comment]
well, those params you need probably won't be boolean but something else, but this gives a good overview of how to add them.

> Do you have any document I can refer to and make changes?
no, not really. But I'm sure you'll be able to google what you need for ios and android.
