### ISSUE TITLE
How to open calendar app in the created event ?

### ISSUE THREAD

**Issue by rodrigofbm** [vonovak/react-native-add-calendar-event#42]
Is there a way to make a button open the calendar in a previously created event?

**Comment by vonovak** [comment]
Currently no, but it's a valid need. I'll add it when I have time,hopefully within 2-3 weeks

**Comment by vonovak** [comment]
@rodrigofbm please try the v2 release candidate and let me know how it works, thanks.

**Comment by vonovak** [comment]
this is released in v2.0, please open a new issue in case there is a problem
