### ISSUE TITLE
Error building in Android: Could not find method google() for arguments [] on repository container 

### ISSUE THREAD

**Issue by nbastoWM** [vonovak/react-native-add-calendar-event#48]
When I run-android it shows me this error:

````
A problem occurred evaluating project ':react-native-add-calendar-event'.
> Could not find method google() for arguments [] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.
````

```
"react": "16.4.1",
"react-native": "0.56.0",
"react-native-add-calendar-event": "^2.1.0",
```

```
ext {
    buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
}

```

I found workarounds for other packages and tried adding `google()` to build.gradle or `exclude group: "com.android.support", module: 'support-v4'` in the compile but with no success.

**Comment by vonovak** [comment]
I guess you'll either need to use newer android gradle plugin (and newer gradle) or downgrade to 2.0.2 - there are no differences in terms of features (https://github.com/vonovak/react-native-add-calendar-event/blob/master/CHANGELOG.md)

**Comment by nbastoWM** [comment]
Thanks! It worked!
