### ISSUE TITLE
AddCalenderEvent.presentNewEventDialog fails with 'undefuned is not an object' on ios

### ISSUE THREAD

**Issue by shrutic** [vonovak/react-native-add-calendar-event#5]
This works fine on Android, but fails on iOs for me. 
I created a podspec in the fork of this project and tried to use it to link instead of following the manual linking described in README. 
https://github.com/shrutic/react-native-add-calendar-event/tree/master 

Is there any restriction on why Podspec does not work for this project and we are restricted to use only the manual linking? 
****
Update: 
Seems like the library is indeed getting hit, but the iOS Native modules are not being recognized and causing the error. Below is the red screen I get when trying to launch on iOS device

![error_calender](https://user-images.githubusercontent.com/4141641/29045033-dc82bede-7b76-11e7-9186-0481c5ba1387.png)

**Comment by itswaze** [comment]
I had this problem, just had to manual link on iOS and it's working now :)

**Comment by shrutic** [comment]
Thanks. I was able to eventually resolve it with a new pod spec file. I sent a pr out with the change. 
Was trying to avoid manual linking in iOS as rest of my project uses Cocoapods

Shruti

**Comment by shrutic** [comment]
This is the pr
https://github.com/vonovak/react-native-add-calendar-event/pull/6

**Comment by vonovak** [comment]
this was resolved by merging the mentioned PR
