### ISSUE TITLE
Cannot Install through npm for react-native @0.59.1

### ISSUE THREAD

**Issue by chukkalasandeep** [vonovak/react-native-add-calendar-event#62]
My current react-native version is 0.59.1, and when I try to run npm install --save  react-native-add-calendar-event then I am getting the below error.

![image](https://user-images.githubusercontent.com/9654621/54699987-0c379b00-4b6d-11e9-980f-7198d399778f.png)

Can someone help on the issue

**Comment by vonovak** [comment]
hi! this is just a warning. it should work fine. That being said, I should fix the version matcher.

**Comment by vonovak** [comment]
fixed in 2.3.1
