### ISSUE TITLE
Outlook calendar is not supported. 

### ISSUE THREAD

**Issue by MayoudP** [vonovak/react-native-add-calendar-event#63]
I have some Android users who are using Outlook calendar to manage their event. But it appears that when using `react-native-add-calendar-event` on my app, it wasn't suggesting them their Outlook app to save the event. 
But no problem with some others applications on their phones (to save on Outlook calendar).

Does anyone know how I can manage that ? Can we do something ? 

Thank's for the help !

**Comment by vonovak** [comment]
I guess we'll need to tweak the intent for this to work..? Would you care to test this? https://github.com/vonovak/react-native-add-calendar-event/blob/39cceb2c31c44d1f4e66091d420d5220a8f6f138/android/src/main/java/com/vonovak/AddCalendarEventModule.java#L91

**Comment by MayoudP** [comment]
Hello there, 
I'm not quite familiar with this. I tried to looks for some tricks, but didn't manage to do anything :/ 
Sorry !

**Comment by Peretz30** [comment]
Added PR #102
