### ISSUE TITLE
AAPT: No resource identifier found for attribute 'appComponentFactory' in package 'android'

### ISSUE THREAD

**Issue by MITDD6338** [vonovak/react-native-add-calendar-event#66]
/Users/iosdeveloper/Meet/XXXXXX/android/app/build/intermediates/manifests/full/release/AndroidManifest.xml:45: 

> AAPT: No resource identifier found for attribute 'appComponentFactory' in package 'android'

    

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> Failed to process resources, see aapt output above for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 40s
162 actionable tasks: 148 executed, 14 up-to-date

**so can you help us?**
Thanks Advance

**Comment by vonovak** [comment]
hello, I'm sorry but given the provided information I have no way to help you, it does not even seem to be related to this package. If you need help, please provide minimal runnable repro. Thanks.
