### ISSUE TITLE
Getting "unparseable date" on Android

### ISSUE THREAD

**Issue by ledfusion** [vonovak/react-native-add-calendar-event#9]
Hi there,

I'm using RN 0.46.1 on an Android 7.0 and react-native-add-calendar-event 0.2.0

The code below works fine on iPhone:

    const eventConfig = {
      title: "Title here",
      startDate: "2017-09-25T08:00:00.000Z",
      endDate: "2017-09-25T09:00:00.000Z",
      location: "Place name"
    };

    AddCalendarEvent.presentNewCalendarEventDialog(eventConfig)
      .then(eventId => {
          console.warn(eventId);
      })
      .catch(error => {
        console.warn(error);
      });

But fails on Android. Logcat outputs the following line (the catch block yields the same as well):

    08-29 12:41:20.731 31223  5763 W ReactNativeJS: { [Error: Unparseable date: "2017-09-25T08:00:00.000Z"] framesToPop: 1, code: 'AddCalendarEvent' }

I've also tried by wrapping the JSON date string with a new Date(...) constructor, but no luck so far.

Is anyone facing the same issue?
Thank you

**Comment by vonovak** [comment]
try double Z (ZZ), as described in readme

**Comment by ledfusion** [comment]
Hi **vonovak**, thanks for your reply

Tried with double Z, but the promise still fails (don't see the Java error on LogCat, though)

    Error: Unparseable date: "2017-08-29T23:00:00.000ZZ"
    at createErrorFromErrorData (NativeModules.js:121)
    at NativeModules.js:78
    at MessageQueue.__invokeCallback (MessageQueue.js:301)
    at MessageQueue.js:118
    at MessageQueue.__guard (MessageQueue.js:228)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:117)
    at debuggerWorker.js:71

Thank you

**Comment by ledfusion** [comment]
Any chance to have a look?
Thank you

**Comment by vonovak** [comment]
just looking at the code. How about adding `'` around `T`? eg. `2017-09-25'T'08:00:00.000Z`

android uses 
```
public static final String DATE_PARSING_FORMAT = "yyyy-MM-dd'T'HH:mm:ss.SSSZ";
...
SimpleDateFormat datetimeFormatter = new SimpleDateFormat(DATE_PARSING_FORMAT);
```

so you can play with that

**Comment by vonovak** [comment]
by the way, I'd recommend using some third party library for dealing with dates, such as moment.js because JavascriptCore (which is used to run react native on devices) handles dates differently from V8 (which is used when debugging, when the code runs on your computer).

**Comment by dieppe** [comment]
See https://stackoverflow.com/a/31091090

This bugs come from the pattern `yyyy-MM-dd'T'HH:mm:ss.SSSZ` which should be `yyyy-MM-dd'T'HH:mm:ss.SSSX` in standard Java or in our case `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'`.

I really don't have time to do a PR (I'm on a very short deadline) right now. If someone can do it great, otherwise I may have time later this month (if I don't forget that is ^^').

Now, on to figure out why the date is not properly showing up in the calendar app :)

**Comment by vonovak** [comment]
@ledfusion so I took a while to take a look at this - and the mistake is actually very silly. Talking about Z/ZZ - these strings are not supposed to be passed to the module, they are supposed to be replaced by the timezone (https://momentjs.com/docs/#/displaying/format/).

passing 

```js
const eventConfig = {
  title: "Title here",
  startDate: "2017-09-25T08:00:00.000Z",
  endDate: "2017-09-25T09:00:00.000Z",
  location: "Place name"
};
```


should be

```js
const eventConfig = {
  title: "Title here",
  startDate: "2017-09-25T08:00:00.000+0600",
  endDate: "2017-09-25T09:00:00.000+0600",
  location: "Place name"
};
```
where +0600 should be the value for your timezone

**Comment by ledfusion** [comment]
Oh, I see
But then... wouldn't it be easier to internally pass the Unix timestamp instead of a formatted string?
This way, the Java side could initialize the date from and integer, and confusion is gone

Thank you

**Comment by vonovak** [comment]
@ledfusion if you come up with a way to do this on iOS as well and ship over a PR, I may consider it

**Comment by dieppe** [comment]
http://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html#iso8601timezone

```
For formatting, if the offset value from GMT is 0, "Z" is produced. If the number of pattern letters is 1, any fraction of an hour is ignored. For example, if the pattern is "X" and the time zone is "GMT+05:30", "+05" is produced.

For parsing, "Z" is parsed as the UTC time zone designator. General time zones are not accepted.
```

The letter `Z` is not recognized in the SimpleDateFormat _pattern_, it should really be `X`. So, you can modify the current pattern to `yyyy-MM-dd'T'HH:mm:ss.SSSX` and it will work (even with a string ending with a `Z` which is a valid timezone indicator meaning UTC or +0).

**Comment by alex1007** [comment]
"react-native-add-calendar-event": "^0.3.0"

```
const event = {
          title: ...,
          startDate: moment.tz(time.start, timezone).format("YYYY-MM-DDTHH:mm:ss.sssZ"),
          endDate: moment.tz(time.end, timezone).format("YYYY-MM-DDTHH:mm:ss.sssZ"),
          location: ...,
          notes: ...
      };
```

    { 
        startDate: "2017-12-14T08:20:00.000+09:00",
        endDate: "2017-12-14T10:00:00.000+09:00",
    }

ios has no exceptions. Only occurred on android

Error: Unparseable date: "2017-12-14T08:20:00.000+09:00" (at offset 23)
    at createErrorFromErrorData (NativeModules.js:115)
    at NativeModules.js:78
    at MessageQueue.__invokeCallback (MessageQueue.js:296)
    at MessageQueue.js:120
    at MessageQueue.__guard (MessageQueue.js:218)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:119)
    at debuggerWorker.js:71

The correct time string will cause error. However, if i pass "2017-12-14T08:20:00.000Z" in the event, it won't throw any exception.

**Comment by ngoctan95** [comment]
Anybody got solution for this? :(

**Comment by mordaha** [comment]
> Anybody got solution for this? :(

```js
moment(date).utc().format('YYYY-MM-DDTHH:mm:ss.SSS\\Z')
```

**Comment by ngoctan95** [comment]
> > Anybody got solution for this? :(
> 
> ```js
> moment(date).utc().format('YYYY-MM-DDTHH:mm:ss.SSS\\Z')
> ```
I want to convert to another timezone, how can I fix that? 
Something likes 2018-12-13T04:00:01.000+08:00
Its not working in Android. Only "Z" works. 
So confused

**Comment by systemride** [comment]
@ngoctan95 The readme is updated now and this works for me:

```
moment(date).utc().format('YYYY-MM-DDTHH:mm:ss.SSS[Z]')
```

**Comment by arnaudambro** [comment]
`new Date(timestamp or ISO).toISOString()` works for me, both in iOS and Android

**Comment by fredcoder** [comment]
This worked for me in both:

`moment(Date,'YYYY-MM-DDTHH:mm:ss.SSS+1000').utc().format('YYYY-MM-DDTHH:mm:ss.SSS[Z]')`

where "+1000" is your time zone

**Comment by studioilgranello** [comment]
> `new Date(timestamp or ISO).toISOString()` works for me, both in iOS and Android

+1
Obviously also `moment(your date).toISOString()` works perfectly on both OS

**Comment by Pulimet** [comment]
Worked for me this way:

`const date = new Date();
let dateStr = date.toISOString(); 
if (isAndroidOs) {
    dateStr = dateStr.replace('Z', '+0000');
}`
