### ISSUE TITLE
Android bundle for release fails because of this

### ISSUE THREAD

**Issue by jeremyfrancis** [vonovak/react-native-add-calendar-event#93]
When I go to bundle my android build for release I get this. However, I think this may happen with other packages too but it may just so happen that react-native-add-calendar-event pops up first. But I'm not fully sure. I cannot figure out for the life of me right now how to get my app to build for android without this occurring. Would love some insight here.

> Task :react-native-add-calendar-event:transformNativeLibsWithMergeJniLibsForRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-add-calendar-event:transformNativeLibsWithMergeJniLibsForRelease'.
> java.io.StreamCorruptedException: invalid type code: 00

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 47s

**Comment by jeremyfrancis** [comment]
Ok simple fix lol...

./gradlew clean

**Comment by vonovak** [comment]
I'm assuming this is no longer an issue.
